// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClrvj7S_1Nk-KmxNy8wDyk3m-BO4CKWvs',
    appId: '1:123688288179:web:468e61263e6174fcf995c6',
    messagingSenderId: '123688288179',
    projectId: 'quizq-app',
    authDomain: 'quizq-app.firebaseapp.com',
    storageBucket: 'quizq-app.appspot.com',
    measurementId: 'G-K5S82WZPXR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAY-mNVC7ytL147kIUNDiyVK36fSxIRVLk',
    appId: '1:123688288179:android:706e7272f569d1e3f995c6',
    messagingSenderId: '123688288179',
    projectId: 'quizq-app',
    storageBucket: 'quizq-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpW1ZPunug6HyS2cpW12FLkYKmDPwrw7E',
    appId: '1:123688288179:ios:febc12c28781a638f995c6',
    messagingSenderId: '123688288179',
    projectId: 'quizq-app',
    storageBucket: 'quizq-app.appspot.com',
    iosBundleId: 'com.engmouaz.quizqFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpW1ZPunug6HyS2cpW12FLkYKmDPwrw7E',
    appId: '1:123688288179:ios:e64b75bd725d2a96f995c6',
    messagingSenderId: '123688288179',
    projectId: 'quizq-app',
    storageBucket: 'quizq-app.appspot.com',
    iosBundleId: 'com.engmouaz.quizqFlutter.RunnerTests',
  );
}
